FROM golang:1.25-alpine

# git нужен для скачивания модулей
RUN apk add --no-cache git

WORKDIR /app

# Сначала зависимости
COPY go.mod go.sum ./
RUN go mod download

# В дев-окружении код будет монтироваться как volume
CMD ["go", "run", "main.go"]